export const GET_ERRORS = "GET_ERRORS";
export const GET_PRODUITS = "GET_PRODUITS";
export const GET_PRODUIT = "GET_PRODUIT";
export const DELETE_PRODUIT = "DELETE_PRODUIT";
export const GET_FOURNISSEURS = "GET_FOURNISSEURS";
export const GET_FOURNISSEUR = "GET_FOURNISSEUR";
export const DELETE_FOURNISSEUR = "DELETE_FOURNISSEUR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
